- repo: local
  hooks:

  - id: mix-format
    name: 'elixir: mix format'
    entry: mix format --check-formatted
    language: system
    files: \.exs*$

  - id: mix-compile
    name: 'elixir: mix compile'
    entry: mix compile --force --warnings-as-errors
    language: system
    pass_filenames: false
    files: \.ex$

  - id: mix-credo
    name: 'elixir: mix credo'
    entry: mix credo --strict
    language: system
    pass_filenames: false
    files: \.exs*$

- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v1.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: no-commit-to-branch
    args: [-b, master, -b, production, -b, staging]
